[package]
name = "execd-brain"
version = "0.1.0"
authors = ["wayofthepie <wayofthepie@gmail.com>"]
edition = "2018"

[dependencies]
actix = "0.7.9"
futures = "0.1.25"
nitox = "0.1.8"
serde =  { version = "1.0.84", features = ["derive"] }
serde_json = "1.0.35"
tokio = "0.1.14"
